-- 创建数据库
CREATE DATABASE IF NOT EXISTS random_numbers_db;
USE random_numbers_db;

-- 创建表
CREATE TABLE IF NOT EXISTS numbers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    random_value INT NOT NULL
);

-- 插入随机数据
INSERT INTO numbers (random_value)
SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual
UNION ALL SELECT FLOOR(RAND() * 101) FROM dual;
